# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Mayank/Desktop/385/pokemon_game/pokemon.srcs/sources_1/ip/bram_20_pkmn/bram_20_pkmn.xci
# IP: The module: 'bram_20_pkmn' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mayank/Desktop/385/pokemon_game/pokemon.gen/sources_1/ip/bram_20_pkmn/bram_20_pkmn_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_20_pkmn'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Mayank/Desktop/385/pokemon_game/pokemon.srcs/sources_1/ip/bram_20_pkmn/bram_20_pkmn.xci
# IP: The module: 'bram_20_pkmn' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Mayank/Desktop/385/pokemon_game/pokemon.gen/sources_1/ip/bram_20_pkmn/bram_20_pkmn_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_20_pkmn'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
