# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/klok1/Documents/ECE385_Pokemon/Provided Code/pin_assignment/urbana_ddr3.xdc

# Block Designs: bd/mb_block/mb_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block || ORIG_REF_NAME==mb_block} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_0/mb_block_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_0 || ORIG_REF_NAME==mb_block_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mig_7series_0_0/mb_block_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mig_7series_0_0 || ORIG_REF_NAME==mb_block_mig_7series_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_xbar_0 || ORIG_REF_NAME==mb_block_xbar_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_periph_0/mb_block_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_axi_intc_0/mb_block_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_block_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_microblaze_0_xlconcat_0/mb_block_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mb_block_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_mdm_1_0/mb_block_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_mdm_1_0 || ORIG_REF_NAME==mb_block_mdm_1_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_rst_mig_7series_0_83M_0/mb_block_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==mb_block_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_uartlite_0_0/mb_block_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_uartlite_0_0 || ORIG_REF_NAME==mb_block_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_axi_timer_0_0/mb_block_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_axi_timer_0_0 || ORIG_REF_NAME==mb_block_axi_timer_0_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_auto_pc_3/mb_block_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_auto_pc_3 || ORIG_REF_NAME==mb_block_auto_pc_3} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_auto_pc_0/mb_block_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_auto_pc_0 || ORIG_REF_NAME==mb_block_auto_pc_0} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_auto_pc_1/mb_block_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_auto_pc_1 || ORIG_REF_NAME==mb_block_auto_pc_1} -quiet] -quiet

# IP: bd/mb_block/ip/mb_block_auto_pc_2/mb_block_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_block_auto_pc_2 || ORIG_REF_NAME==mb_block_auto_pc_2} -quiet] -quiet

# XDC: c:/Users/klok1/Documents/ECE385_DDR3/ECE385_DDR3.gen/sources_1/bd/mb_block/mb_block_ooc.xdc
