# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/klok1/Documents/ECE385_Pokemon/ECE385_Pokemon.srcs/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0.xci
# IP: The module: 'mb_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/klok1/Documents/ECE385_Pokemon/ECE385_Pokemon.gen/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/klok1/Documents/ECE385_Pokemon/ECE385_Pokemon.srcs/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0.xci
# IP: The module: 'mb_block_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/klok1/Documents/ECE385_Pokemon/ECE385_Pokemon.gen/sources_1/bd/mb_block/ip/mb_block_xbar_0/mb_block_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_block_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
