# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pin_assignment/mb_usb_hdmi_top.xdc

# IP: ip/pokemon_sprites/pokemon_sprites.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pokemon_sprites || ORIG_REF_NAME==pokemon_sprites} -quiet] -quiet

# Block Designs: bd/mb_usb/mb_usb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb || ORIG_REF_NAME==mb_usb} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_0/mb_usb_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_0 || ORIG_REF_NAME==mb_usb_microblaze_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_v10_0/mb_usb_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_v10_0 || ORIG_REF_NAME==mb_usb_dlmb_v10_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_v10_0/mb_usb_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_v10_0 || ORIG_REF_NAME==mb_usb_ilmb_v10_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_dlmb_bram_if_cntlr_0/mb_usb_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_usb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_ilmb_bram_if_cntlr_0/mb_usb_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mb_usb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_lmb_bram_0/mb_usb_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_lmb_bram_0 || ORIG_REF_NAME==mb_usb_lmb_bram_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xbar_0/mb_usb_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xbar_0 || ORIG_REF_NAME==mb_usb_xbar_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_periph_0/mb_usb_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_microblaze_0_axi_intc_0/mb_usb_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mb_usb_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_mdm_1_0/mb_usb_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_mdm_1_0 || ORIG_REF_NAME==mb_usb_mdm_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_clk_wiz_1_0/mb_usb_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_clk_wiz_1_0 || ORIG_REF_NAME==mb_usb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_rst_clk_wiz_1_100M_0/mb_usb_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mb_usb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_axi_uartlite_0_0/mb_usb_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_axi_uartlite_0_0 || ORIG_REF_NAME==mb_usb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_gpio_usb_keycode_0/mb_usb_gpio_usb_keycode_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_gpio_usb_keycode_0 || ORIG_REF_NAME==mb_usb_gpio_usb_keycode_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_gpio_usb_rst_0/mb_usb_gpio_usb_rst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_gpio_usb_rst_0 || ORIG_REF_NAME==mb_usb_gpio_usb_rst_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_gpio_usb_int_0/mb_usb_gpio_usb_int_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_gpio_usb_int_0 || ORIG_REF_NAME==mb_usb_gpio_usb_int_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_timer_usb_axi_0/mb_usb_timer_usb_axi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_timer_usb_axi_0 || ORIG_REF_NAME==mb_usb_timer_usb_axi_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_spi_usb_0/mb_usb_spi_usb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_spi_usb_0 || ORIG_REF_NAME==mb_usb_spi_usb_0} -quiet] -quiet

# IP: bd/mb_usb/ip/mb_usb_xlconcat_0_0/mb_usb_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mb_usb_xlconcat_0_0 || ORIG_REF_NAME==mb_usb_xlconcat_0_0} -quiet] -quiet

# XDC: c:/Users/Mayank/Desktop/385/lab6/lab6.gen/sources_1/bd/mb_usb/mb_usb_ooc.xdc
